version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  lint:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm
          cache-key: 'npm-{{ checksum "package-lock.json" }}'

      - run:
          name: Run ESLint
          command: npm run lint

      - run:
          name: Check formatting
          command: npm run format:check

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - main
